apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.port }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-grafana