apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dlstreamer-pipeline-server
spec:
  selector:
    app: {{ .Release.Name }}-dlstreamer-pipeline-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: dlstreamer-pipeline-server-8080
    - protocol: TCP
      port: 8555
      targetPort: 8555
      name: dlstreamer-pipeline-server-8555