apiVersion: v1
kind: Service
metadata:
  name: influxdb2
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.influxdb.service.type }}
  selector:
    app: {{ .Release.Name }}-influxdb
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.influxdb.service.port }}
      targetPort: {{ .Values.influxdb.service.port }}
