apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-influxdb-config
  namespace: {{ .Release.Namespace }}
data:
  influxdb.conf: |
    [meta]
      dir = "/var/lib/influxdb2/meta"
    [data]
      dir = "/var/lib/influxdb2/data"
      wal-dir = "/var/lib/influxdb2/wal"