apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dlstreamer-pipeline-server
  namespace: {{ .Release.Namespace }}
data:
  # Enable RTSP streaming
  ENABLE_RTSP: "true"
  # Enable WebRTC streaming
  ENABLE_WEBRTC: "true"
  # WebRTC signaling server URL
  WEBRTC_SIGNALING_SERVER: "ws://localhost:8443"
  # Run mode for the application
  RUN_MODE: "EVA"
  # GenICam device type
  GENICAM: "Balluff"
  # Detection device type
  DETECTION_DEVICE: "CPU"
  # Classification device type
  CLASSIFICATION_DEVICE: "CPU"
  # Add UTC time to metadata
  ADD_UTCTIME_TO_METADATA: "true"
  # Append pipeline name to publisher topic
  APPEND_PIPELINE_NAME_TO_PUBLISHER_TOPIC: "false"
  # REST server port
  REST_SERVER_PORT: "8080"
  # MQTT server host
  MQTT_HOST: "broker.scenescape.intel.com"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dlstreamer-pipeline-server-config
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
{{ .Files.Get "files/dlstreamer-pipeline-server/config.json" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dlstreamer-pipeline-server-udf
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
{{ .Files.Get "files/dlstreamer-pipeline-server/user_scripts/gvapython/sscape/sscape_adapter.py" | indent 4 }}
