apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-dlstreamer-pipeline-server-rootcert
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  root-cert: {{ .Files.Get "files/secrets/certs/scenescape-ca.pem" | b64enc | quote }}
