apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-nodered-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  influxdb2-admin-token: {{ .Files.Get "files/secrets/influxdb2/influxdb2-admin-token" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-nodered-rootcert
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  root-cert: {{ .Files.Get "files/secrets/certs/scenescape-ca.pem" | b64enc | quote }}
  broker-cert: {{ .Files.Get "files/secrets/certs/scenescape-broker.crt" | b64enc | quote }}
  broker-key: {{ .Files.Get "files/secrets/certs/scenescape-broker.key" | b64enc | quote }}